name: Dev Build and Release

permissions:
  contents: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: true

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.17.0-dev.1786+75044cb04

      - name: Generic Build (aarch64)
        run: zig build -Darch=aarch64

      - name: Generic Build (riscv64)
        run: zig build -Darch=riscv64

      - name: Generic Build (x86_64)
        run: zig build -Darch=x86_64

      - name: Raspberry Pi4 Build
        run: zig build -Dboard=raspberry_pi4

      - name: Raspberry Pi3 Build
        run: zig build -Dboard=raspberry_pi3

      - name: Generate Changelog
        run: |
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          if git rev-parse refs/tags/dev >/dev/null 2>&1; then
            echo "Here are the latest changes since the previous build:" >> $GITHUB_ENV
            echo "" >> $GITHUB_ENV
            git log refs/tags/dev..HEAD --format="- %s (\`%h\`)" >> $GITHUB_ENV
          else
            echo "First development release (or previous tag not found)." >> $GITHUB_ENV
            echo "" >> $GITHUB_ENV
            git log -10 --format="- %s (\`%h\`)" >> $GITHUB_ENV
          fi
          echo "EOF" >> $GITHUB_ENV

      - name: Clean and Recreate dev tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git push --delete origin dev || true
          git tag -d dev || true

          git tag dev
          git push origin dev

      - name: Update Development Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: "dev"
          name: "Development Build"
          body: ${{ env.CHANGELOG }}
          prerelease: true
          files: |
            zig-out/violet-aarch64.img
            zig-out/violet-riscv64.img
            zig-out/violet-x86_64.img
            zig-out/violet-raspberry_pi4.img
            zig-out/violet-raspberry_pi3.img
            LICENSE
            NOTICE.md
            README.md
            SUPPORT.md
